version: "3.8"

# Services
services:
  frontend:
    build: ./frontend
    ports:
      - 8088:80
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d

  # Nginx Service
  nginx:
    image: nginx:1.21
    ports:
      - 8086:80
    volumes:
      - ./backend:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./backend
    working_dir: /var/www/php
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SECRET_JWT_KEY=velice_tajny_klucik
    command: sh -c "php ./db/admins.php && php-fpm"

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: webte2_sz
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.database:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --password=root
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
